package com.qhit.lh.g4.ZWK.T05.bean;
// Generated 2017-12-20 18:03:58 by Hibernate Tools 5.0.6.Final

/**
 * TbUser generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;
	private String birthday;
	private String sex;
	private Integer active;

	public TbUser() {
	}

	public TbUser(String uname, String upwd) {
		this.uname = uname;
		this.upwd = upwd;
	}

	public TbUser(String uname, String upwd, String birthday, String sex, Integer active) {
		this.uname = uname;
		this.upwd = upwd;
		this.birthday = birthday;
		this.sex = sex;
		this.active = active;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public TbUser(Integer uid, String uname, String upwd, String birthday, String sex, Integer active) {
		super();
		this.uid = uid;
		this.uname = uname;
		this.upwd = upwd;
		this.birthday = birthday;
		this.sex = sex;
		this.active = active;
	}

}
